import type { Movie } from "./types"

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: "Dune: Parte Dos",
    overview: "Paul Atreides se une a los Fremen mientras busca venganza contra los conspiradores que destruyeron a su familia. Enfrentando una elección entre el amor de su vida y el destino del universo, debe evitar un terrible futuro que solo él puede prever.",
    posterPath: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    releaseDate: "2024-02-27",
    rating: 8.4,
    genres: ["Ciencia Ficcion", "Aventura"],
    runtime: 166,
    director: "Denis Villeneuve",
    cast: ["Timothee Chalamet", "Zendaya", "Rebecca Ferguson", "Josh Brolin"]
  },
  {
    id: 2,
    title: "Oppenheimer",
    overview: "La historia del fisico estadounidense J. Robert Oppenheimer y su papel en el desarrollo de la bomba atomica.",
    posterPath: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    releaseDate: "2023-07-19",
    rating: 8.1,
    genres: ["Drama", "Historia"],
    runtime: 180,
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."]
  },
  {
    id: 3,
    title: "Poor Things",
    overview: "La increible historia de Bella Baxter, una joven devuelta a la vida por el brillante y poco ortodoxo cientifico Dr. Godwin Baxter.",
    posterPath: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    releaseDate: "2023-12-07",
    rating: 7.9,
    genres: ["Comedia", "Romance", "Ciencia Ficcion"],
    runtime: 141,
    director: "Yorgos Lanthimos",
    cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe"]
  },
  {
    id: 4,
    title: "The Batman",
    overview: "Cuando un asesino en serie marca a victimas de elite en Ciudad Gotica, Batman investiga una conspiracion que desenmascara la corrupcion de la ciudad.",
    posterPath: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
    releaseDate: "2022-03-01",
    rating: 7.7,
    genres: ["Crimen", "Misterio", "Accion"],
    runtime: 176,
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoe Kravitz", "Paul Dano", "Colin Farrell"]
  },
  {
    id: 5,
    title: "Everything Everywhere All at Once",
    overview: "Una inmigrante china que se siente abrumada debe conectar con versiones de si misma del multiverso para detener a un poderoso ser.",
    posterPath: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    releaseDate: "2022-03-11",
    rating: 8.0,
    genres: ["Accion", "Aventura", "Ciencia Ficcion"],
    runtime: 139,
    director: "Daniel Kwan, Daniel Scheinert",
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "Jamie Lee Curtis"]
  },
  {
    id: 6,
    title: "Interstellar",
    overview: "Un grupo de exploradores viaja a traves de un agujero de gusano en el espacio en un intento de asegurar la supervivencia de la humanidad.",
    posterPath: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    releaseDate: "2014-11-05",
    rating: 8.6,
    genres: ["Aventura", "Drama", "Ciencia Ficcion"],
    runtime: 169,
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"]
  },
  {
    id: 7,
    title: "Parasite",
    overview: "Toda la familia de Ki-taek esta desempleada. Cuando su hijo mayor consigue un trabajo como tutor privado, se infiltran en una familia rica.",
    posterPath: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    releaseDate: "2019-05-30",
    rating: 8.5,
    genres: ["Comedia", "Thriller", "Drama"],
    runtime: 132,
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"]
  },
  {
    id: 8,
    title: "Spider-Man: Across the Spider-Verse",
    overview: "Miles Morales viaja a traves del multiverso y conoce un equipo de Spider-People. Cuando los heroes chocan, Miles debe redefinir lo que significa ser un heroe.",
    posterPath: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    releaseDate: "2023-05-31",
    rating: 8.4,
    genres: ["Animacion", "Accion", "Aventura"],
    runtime: 140,
    director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Jake Johnson"]
  },
  {
    id: 9,
    title: "The Grand Budapest Hotel",
    overview: "Las aventuras de Gustave H, el legendario conserje de un famoso hotel europeo, y Zero Moustafa, el chico de los recados que se convierte en su amigo mas confiable.",
    posterPath: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/nX5XotM9yprCKarRH4fzOq1VM1J.jpg",
    releaseDate: "2014-02-26",
    rating: 8.1,
    genres: ["Comedia", "Drama"],
    runtime: 99,
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "Tony Revolori", "F. Murray Abraham", "Adrien Brody"]
  },
  {
    id: 10,
    title: "Blade Runner 2049",
    overview: "Un joven blade runner descubre un secreto largamente enterrado que lo lleva a buscar a Rick Deckard, un ex blade runner que ha estado desaparecido por 30 anos.",
    posterPath: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    releaseDate: "2017-10-04",
    rating: 7.5,
    genres: ["Ciencia Ficcion", "Drama"],
    runtime: 164,
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Jared Leto"]
  },
  {
    id: 11,
    title: "Whiplash",
    overview: "Un joven baterista de jazz persigue la perfeccion a cualquier costo bajo la tutela de un instructor despiadado.",
    posterPath: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg",
    releaseDate: "2014-10-10",
    rating: 8.4,
    genres: ["Drama", "Musica"],
    runtime: 106,
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist", "Paul Reiser"]
  },
  {
    id: 12,
    title: "Mad Max: Fury Road",
    overview: "En un mundo postapocaliptico, Max se une a una guerrera rebelde para huir de un tirano que controla el suministro de agua.",
    posterPath: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdropPath: "https://image.tmdb.org/t/p/original/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg",
    releaseDate: "2015-05-13",
    rating: 8.1,
    genres: ["Accion", "Aventura", "Ciencia Ficcion"],
    runtime: 120,
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"]
  }
]
